CREATE DATABASE IF NOT EXISTS gym_management DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE gym_management;

CREATE TABLE sys_user (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  nickname VARCHAR(50),
  phone VARCHAR(20),
  email VARCHAR(100),
  avatar VARCHAR(255),
  user_type VARCHAR(20) NOT NULL,
  related_business_id BIGINT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE sys_role (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  role_code VARCHAR(50) NOT NULL UNIQUE,
  role_name VARCHAR(50) NOT NULL,
  remark VARCHAR(255),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE member_level (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  level_name VARCHAR(50) NOT NULL,
  level_value INT NOT NULL DEFAULT 1,
  discount_rate DECIMAL(5,2) NOT NULL DEFAULT 100.00,
  description VARCHAR(255),
  status TINYINT NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE member (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  member_no VARCHAR(50) NOT NULL UNIQUE,
  name VARCHAR(50) NOT NULL,
  gender TINYINT NULL,
  phone VARCHAR(20) NOT NULL UNIQUE,
  birthday DATE NULL,
  avatar VARCHAR(255),
  level_id BIGINT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  register_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  remark VARCHAR(255),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE member_package (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  package_name VARCHAR(100) NOT NULL,
  package_type VARCHAR(20) NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  duration_days INT NULL,
  session_count INT NULL,
  description VARCHAR(500),
  status TINYINT NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE member_order (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  order_no VARCHAR(50) NOT NULL UNIQUE,
  member_id BIGINT NOT NULL,
  package_id BIGINT NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  discount_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  payable_amount DECIMAL(10,2) NOT NULL,
  payment_status VARCHAR(20) NOT NULL DEFAULT 'UNPAID',
  order_status VARCHAR(20) NOT NULL DEFAULT 'CREATED',
  audit_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  payment_method VARCHAR(20),
  paid_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE coach (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  coach_no VARCHAR(50) NOT NULL UNIQUE,
  name VARCHAR(50) NOT NULL,
  gender TINYINT NULL,
  phone VARCHAR(20) UNIQUE,
  specialty VARCHAR(255),
  introduction TEXT,
  status TINYINT NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE course_category (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  category_name VARCHAR(50) NOT NULL,
  description VARCHAR(255),
  status TINYINT NOT NULL DEFAULT 1
);

CREATE TABLE course (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  course_name VARCHAR(100) NOT NULL,
  course_type VARCHAR(20) NOT NULL,
  category_id BIGINT NULL,
  coach_id BIGINT NULL,
  duration_minutes INT NOT NULL DEFAULT 60,
  capacity INT NULL,
  description VARCHAR(500),
  status TINYINT NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE feedback_review (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  member_id BIGINT NOT NULL,
  target_type VARCHAR(20) NOT NULL,
  target_id BIGINT NOT NULL,
  rating TINYINT NOT NULL,
  content VARCHAR(1000),
  audit_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE equipment (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  equipment_no VARCHAR(50) NOT NULL UNIQUE,
  equipment_name VARCHAR(100) NOT NULL,
  category_id BIGINT NULL,
  quantity INT NOT NULL DEFAULT 0,
  available_quantity INT NOT NULL DEFAULT 0,
  location VARCHAR(100),
  status VARCHAR(20) NOT NULL DEFAULT 'NORMAL',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE banner (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(100),
  image_url VARCHAR(255) NOT NULL,
  link_url VARCHAR(255),
  sort_no INT NOT NULL DEFAULT 0,
  status TINYINT NOT NULL DEFAULT 1
);
